#port
server:
  port: 8001
#mybaits log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com.sunlx.serviceedu/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0


spring:
  datasource:
    #url: jdbc:mysql://81.70.41.63:3306/edu?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/learn?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    #password: 123456
    password: 123Qaz!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 600000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

